services:
  - type: web
    name: portfolio-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: EMAIL_HOST_USER
        value: bannavirru6@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
